# =============================================================================
# Booth Board — Production Dockerfile
# =============================================================================
# Multi-stage build for the Next.js 16 jet ski booth board.
#
# Why this shape (deviation note for the kit's templates):
#   - The kit's Dockerfile.app.template assumes an `apps/<name>/` workspace
#     layout. The jet repo is a flat single-app layout (see pnpm-workspace.yaml
#     — no `packages:` field).
#   - Storage is PostgreSQL (Neon in production, local Docker Postgres in dev)
#     reached via the node-postgres `pg` driver behind a single DATABASE_URL.
#     `pg` is pure JavaScript — there is NO native addon to compile, so the
#     builder stage needs no python3 / make / g++ and the runner needs no
#     libc6-compat shim for a database driver. (The SQLite-era better-sqlite3
#     native build is gone.)
#   - Schema is provisioned by REAL drizzle-kit migrations applied FROM OUTSIDE
#     this image — by the deploy pipeline (a CI migrate step against the Neon
#     URL) or by host tooling in dev (`pnpm db:migrate`). drizzle-kit is a
#     devDependency and is intentionally ABSENT from this production standalone
#     image: a runtime container should not carry, or be able to run, schema
#     migrations. No lazy `CREATE TABLE` bootstrap runs at boot anymore.
#   - We use Next.js `output: 'standalone'` (configured in next.config.ts) so
#     the runner image only carries the traced server bundle + static + public,
#     not the whole node_modules.
# =============================================================================

ARG NODE_VERSION=22-alpine

# -----------------------------------------------------------------------------
# Stage 1 — builder: install deps, build the standalone Next bundle.
# -----------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy lockfiles + workspace manifest first for cached layer reuse.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc* ./

# The repo's flat layout means the `packages/` tree (nucleus core) is resolved
# via tsconfig paths, not pnpm workspaces. Copying it after dependency install
# keeps it out of the pnpm install layer.
RUN pnpm install --frozen-lockfile

# Copy the rest of the source tree.
COPY . .

# Build the standalone Next.js bundle.
# `pnpm build` runs `next build`; with `output: 'standalone'` in
# next.config.ts, this writes:
#   .next/standalone/      ← minimal Node server + traced deps
#   .next/static/          ← hashed client assets
# The runner stage copies those three.
#
# next build's "collect page data" phase imports the bookings module graph,
# which constructs the pg Pool at module load. The Pool is lazy (no connection
# until first query) and app/page.tsx is force-dynamic (no query at build), so a
# throwaway placeholder is enough to get past database.ts's required-env guard.
# The REAL DATABASE_URL is injected at RUNTIME (compose sets the in-network URL;
# production sets Neon's). This ENV lives only in the builder stage and never
# reaches the runner image.
ENV DATABASE_URL="postgres://placeholder-build-only:not-a-real-secret@127.0.0.1:5432/build_time_placeholder_db"
RUN pnpm build

# -----------------------------------------------------------------------------
# Stage 2 — runner: slim Node image, non-root user, standalone server.
# -----------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS runner

# `curl` is the only OS package the runtime needs — the Docker healthcheck
# below shells out to it. `pg` is pure JS, so no libc6-compat / native shim.
RUN apk add --no-cache curl

ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Non-root user. Next.js standalone runs fine as a non-root UID.
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

WORKDIR /app

# The standalone bundle is self-contained: it ships its own minimal
# node_modules tracing what server.js actually imports (including the pure-JS
# `pg` driver). Three copies and nothing more.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# Healthcheck — Docker hits this on the configured interval. The compose file
# defines a richer healthcheck; this is the in-image default for `docker run`
# users who skip compose.
HEALTHCHECK --interval=10s --timeout=3s --start-period=15s --retries=3 \
  CMD curl -fsS http://localhost:3000/ || exit 1

# server.js is generated by Next's standalone build and starts the server on
# $PORT / $HOSTNAME. It reads DATABASE_URL from the environment (set by compose
# in dev, by the deploy/Vercel env in production).
CMD ["node", "server.js"]
