// =============================================================================
// Audit Module — IAuditEventRepository Interface
// =============================================================================
// Contract only — defines what the repository does, not how it does it.
// Implementations live in infrastructure/repositories/.
//
// Append-only, immutable design (SPEC DEC-AU2 / AC-4):
//   - append() is the sole write method. No update, no delete, no softDelete.
//   - The interface itself enforces app-level append-only so no caller can
//     accidentally try to update or delete an audit event.
//   - Belt-and-suspenders: a DB-level trigger also REJECTs any UPDATE/DELETE
//     (SPEC DEC-AU2 / archie migration 0001_audit_events_immutability_trigger.sql).
//
// Bounded reads (donnie-rules §2 — unbounded queries are forbidden):
//   - findByEntity: bounded by a hard LIMIT per entity lookup.
// =============================================================================

import type { AuditEvent } from './types';

export type IAuditEventRepository = {
  /**
   * Append one immutable audit event. This is the only write path.
   * The id is generated by the schema $defaultFn (cuid2) if not provided.
   */
  append: (event: AuditEvent) => Promise<void>;

  /**
   * Return all events for a given entityId (soft link), newest first.
   * Bounded by limit to avoid unbounded scans on high-volume entities.
   *
   * @param entityId The soft-link entity id (e.g., a booking id string).
   * @param limit    Maximum rows to return.
   */
  findByEntity: (entityId: string, limit: number) => Promise<AuditEvent[]>;
};
