#!/usr/bin/env bash
# =============================================================================
# compose.sh — docker compose wrapper for the Nucleus Stack Kit
# =============================================================================
# Wraps `docker compose` with:
#   - explicit -f (the right file per profile, from manifest.yaml)
#   - explicit -p (the compose project name = <slug>_<worktree>[_<ephemeral>])
#   - environment with STACK_PORT_* injected so compose files can reference them
#   - workdir = repo root (so relative paths resolve)
# =============================================================================

[[ -n "${_STACK_COMPOSE_LOADED:-}" ]] && return 0
_STACK_COMPOSE_LOADED=1

# shellcheck source=./_common.sh
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"
# shellcheck source=./ports.sh
source "$(dirname "${BASH_SOURCE[0]}")/ports.sh"

# Compute compose project name from slug+worktree[+ephemeral_suffix].
#
# Honors STACK_COMPOSE_PROJECT_OVERRIDE — set by `lib/sandbox.sh` so that
# every existing helper (stack ps/logs/psql/exec/lifecycle/seed) routes to the
# scoped sandbox's containers when the user invokes `stack sandbox <id> <verb>`.
stack_compose_project_name() {
  if [[ -n "${STACK_COMPOSE_PROJECT_OVERRIDE:-}" ]]; then
    printf "%s" "$STACK_COMPOSE_PROJECT_OVERRIDE"
    return 0
  fi
  local key=${1:-${STACK_KEY:-}}
  if [[ -z "$key" ]]; then
    local slug worktree
    slug=$(stack_project_slug)
    worktree=$(stack_current_worktree)
    key="${slug}@${worktree}"
  fi
  # docker-compose accepts lowercase alphanumerics + hyphens + underscores.
  printf "%s" "$key" | tr '@' '_' | tr '#' '_' | tr '/' '-' | tr '[:upper:]' '[:lower:]'
}

# The single entry point — wraps docker compose with profile awareness.
# Use: stack_compose <profile> <subcommand> [args...]
#
# Honors STACK_COMPOSE_EXTRA_FILES — colon-separated list of additional `-f`
# files to layer on top of the project's compose file. Used by `lib/sandbox.sh`
# to inject a per-instance override that clears `ports:` arrays (so sandboxes
# never bind host ports).
stack_compose() {
  local profile=$1; shift
  local compose_file proj
  compose_file=$(stack_compose_file "$profile")
  [[ -n "$compose_file" ]] || stack_die "no compose file configured for profile=$profile"
  [[ -f "$STACK_REPO_ROOT/$compose_file" ]] || stack_die "compose file not found: $compose_file"
  proj=$(stack_compose_project_name)

  # Build extra -f arguments from STACK_COMPOSE_EXTRA_FILES (colon-separated).
  local -a extra_args=()
  if [[ -n "${STACK_COMPOSE_EXTRA_FILES:-}" ]]; then
    local IFS=':'
    for f in $STACK_COMPOSE_EXTRA_FILES; do
      [[ -n "$f" ]] && [[ -f "$f" ]] && extra_args+=( -f "$f" )
    done
  fi

  (
    cd "$STACK_REPO_ROOT"
    if [[ -f "infra/.ports" ]]; then
      set -a; source "infra/.ports"; set +a
    fi
    if [[ -f "infra/.env" ]]; then
      set -a; source "infra/.env"; set +a
    fi
    docker compose -f "$compose_file" "${extra_args[@]}" -p "$proj" "$@"
  )
}

# Auto-generate a port override snippet for the current profile.
# Compose files that ARE port-aware should reference $STACK_PORT_* directly.
# For projects that haven't migrated yet, generate a compose.override.yml that
# remaps the standard ports → allocated ports.
stack_compose_port_override() {
  local profile=$1
  local out="$STACK_REPO_ROOT/infra/.compose.override.yml"

  : "${STACK_PORT_APP:?ports not allocated; run stack_ensure_ports first}"
  : "${STACK_PORT_DB:?ports not allocated; run stack_ensure_ports first}"

  cat >"$out" <<EOF
# Generated by Nucleus Stack Kit — do not edit by hand.
# Maps standard internal ports to the worktree's allocated host ports.
# Re-generated on every \`stack up\`.
services:
EOF

  local svc_app svc_db svc_proxy
  svc_app=$(stack_service_app)
  svc_db=$(stack_service_db)
  svc_proxy=$(stack_service_proxy)

  # Only override ports for services that exist in the compose file.
  # Detection: grep the service name. Crude but effective.
  local compose_file
  compose_file=$(stack_compose_file "$profile")
  local compose_path="$STACK_REPO_ROOT/$compose_file"

  if grep -qE "^[[:space:]]+${svc_app}:" "$compose_path" 2>/dev/null; then
    cat >>"$out" <<EOF
  $svc_app:
    ports:
      - "${STACK_PORT_APP}:4100"
EOF
  fi

  if grep -qE "^[[:space:]]+${svc_db}:" "$compose_path" 2>/dev/null; then
    cat >>"$out" <<EOF
  $svc_db:
    ports:
      - "127.0.0.1:${STACK_PORT_DB}:5432"
EOF
  fi

  if grep -qE "^[[:space:]]+${svc_proxy}:" "$compose_path" 2>/dev/null; then
    cat >>"$out" <<EOF
  $svc_proxy:
    ports:
      - "${STACK_PORT_PROXY_HTTP:-8080}:80"
      - "${STACK_PORT_PROXY_HTTPS:-9443}:443"
EOF
  fi

  printf "%s" "$out"
}

# Returns the host port that the running compose project has bound to
# <service>:<internal_port>, or "0" if no host binding exists. Uses `docker
# compose port` so the answer always matches reality, regardless of whether the
# kit's port-override is enabled.
#
# Output: a bare port number (e.g. "443") or "0".
stack_bound_port() {
  local profile=$1 service=$2 internal_port=$3
  local compose_file proj out
  compose_file=$(stack_compose_file "$profile")
  proj=$(stack_compose_project_name)
  out=$(cd "$STACK_REPO_ROOT" && docker compose -f "$compose_file" -p "$proj" port "$service" "$internal_port" 2>/dev/null) || true
  # `docker compose port` prints "0.0.0.0:NNNN" or "127.0.0.1:NNNN" when bound,
  # ":0" or empty when not. Take the suffix after the last colon.
  local port="${out##*:}"
  if [[ -z "$port" ]] || [[ "$port" == "0" ]]; then
    printf "0"
  else
    printf "%s" "$port"
  fi
}

# Wraps stack_compose to also include the auto-generated override.
# Respects features.compose_port_override in the manifest:
#   true  → generate + use the override (port remap on every up)
#   false → skip the override entirely; the project's own compose ports apply
stack_compose_with_override() {
  local profile=$1; shift
  local enabled
  enabled=$(stack_manifest features.compose_port_override false)

  if [[ "$enabled" != "true" ]]; then
    # Override disabled — defer to the project's own compose file as-is.
    stack_compose "$profile" "$@"
    return $?
  fi

  local override compose_file proj
  override=$(stack_compose_port_override "$profile")
  compose_file=$(stack_compose_file "$profile")
  proj=$(stack_compose_project_name)

  (
    cd "$STACK_REPO_ROOT"
    [[ -f "infra/.ports" ]] && { set -a; source "infra/.ports"; set +a; }
    [[ -f "infra/.env" ]]   && { set -a; source "infra/.env";   set +a; }
    docker compose -f "$compose_file" -f "$override" -p "$proj" "$@"
  )
}
