#!/usr/bin/env bash
# =============================================================================
# sandbox.sh — Ad-hoc, short-lived, isolated stack instances
# =============================================================================
# A sandbox is a fully isolated copy of the project's stack — own containers,
# own DB volume, own network — designed for testing, scenarios, AI workflows.
# Multiple sandboxes can run in parallel. They have a TTL (default 1h) after
# which they are auto-reaped on the next `stack` invocation.
#
# Host ports: NONE. Sandboxes never bind a host port — collision-free by
# construction. The AI / user accesses everything via `docker compose exec`,
# routed through `stack sandbox <id> {exec|psql|logs|seed|lifecycle|ps}`.
#
# State: ~/.stack/registry.json (the same registry the dashboard reads),
# extended with kind="sandbox", expires_at, ttl_seconds, override_file.
#
# Naming: ID is `<slug>-sandbox-<6-char-hex>` (e.g. demoapp-sandbox-a3f4d1).
# Compose project name derives by replacing dashes with underscores.
# =============================================================================

[[ -n "${_STACK_SANDBOX_LOADED:-}" ]] && return 0
_STACK_SANDBOX_LOADED=1

# shellcheck source=./_common.sh
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"
# shellcheck source=./compose.sh
source "$(dirname "${BASH_SOURCE[0]}")/compose.sh"
# shellcheck source=./state.sh
source "$(dirname "${BASH_SOURCE[0]}")/state.sh"
# shellcheck source=./lifecycle.sh
source "$(dirname "${BASH_SOURCE[0]}")/lifecycle.sh"

STACK_SANDBOX_RUN_DIR="$STACK_HOME/run"
STACK_SANDBOX_MAX_DEFAULT=10

# -----------------------------------------------------------------------------
# ID + project-name helpers
# -----------------------------------------------------------------------------

# Generate a fresh sandbox ID: <slug>-sandbox-<6-char-hex>.
stack_sandbox_new_id() {
  local slug suffix
  slug=$(stack_project_slug)
  # 6 hex chars from /dev/urandom — portable on macOS + Linux.
  suffix=$(od -An -N3 -txC /dev/urandom 2>/dev/null | tr -d ' \n' | head -c 6)
  [[ -z "$suffix" ]] && suffix=$(stack_sha256 "$(date +%s%N)$$$RANDOM" | cut -c1-6)
  printf "%s-sandbox-%s" "$slug" "$suffix"
}

# Compose project name for a sandbox ID. Replaces dashes with underscores
# (docker compose accepts both but underscores are the historical norm).
stack_sandbox_compose_project() {
  local id=$1
  printf "%s" "$id" | tr '-' '_'
}

# Path to the per-instance compose override file.
stack_sandbox_override_path() {
  local id=$1
  printf "%s/sandbox-%s.compose.yml" "$STACK_SANDBOX_RUN_DIR" "$id"
}

# Generate the per-instance override file. Clears `ports:` for every service
# declared in the manifest, so the sandbox never binds host ports.
stack_sandbox_write_override() {
  local id=$1
  mkdir -p "$STACK_SANDBOX_RUN_DIR"
  local path
  path=$(stack_sandbox_override_path "$id")

  local svc_app svc_db svc_proxy
  svc_app=$(stack_service_app)
  svc_db=$(stack_service_db)
  svc_proxy=$(stack_service_proxy)

  # Compose v2 MERGES sequences across -f files by default — so `ports: []`
  # would be a no-op (caddy still tries to bind 80/443 from the parent file).
  # We use the `!reset` tag (compose v2.24+) to explicitly clear the inherited
  # ports array. Mario's machine is on v5.x so this is safe.
  {
    printf "# Generated by Nucleus Stack Kit — do not edit by hand.\n"
    printf "# Sandbox: %s\n" "$id"
    printf "# Clears host port bindings for every project service so sandboxes never collide.\n"
    printf "# Uses YAML !reset tag (compose v2.24+) to replace the inherited 'ports' array.\n"
    printf "services:\n"
    for svc in "$svc_app" "$svc_db" "$svc_proxy"; do
      [[ -z "$svc" ]] && continue
      printf "  %s:\n" "$svc"
      printf "    ports: !reset []\n"
    done
  } > "$path"

  printf "%s" "$path"
}

# -----------------------------------------------------------------------------
# Context loader — called when invoking a scoped subcommand
# -----------------------------------------------------------------------------

# Load a sandbox's context into the environment so subsequent stack_compose /
# cmd_* calls route to its containers. Returns non-zero if the sandbox is not
# found in the registry.
stack_sandbox_load_context() {
  local id=$1
  local entry
  entry=$(python3 - "$STACK_REGISTRY" "$id" <<'PY'
import json, sys
file, target = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(1)
for inst in data.get("instances", []):
    if inst.get("id") == target and inst.get("kind") == "sandbox":
        print(json.dumps(inst))
        sys.exit(0)
sys.exit(1)
PY
) || {
    stack_fail "Sandbox not found: $id" \
               "List active sandboxes:  stack sandbox list"
    return 1
  }

  local cproj override
  cproj=$(printf "%s" "$entry" | python3 -c "import sys,json;print(json.load(sys.stdin)['compose_project'])")
  override=$(printf "%s" "$entry" | python3 -c "import sys,json;print(json.load(sys.stdin).get('override_file',''))")

  export STACK_COMPOSE_PROJECT_OVERRIDE="$cproj"
  if [[ -n "$override" ]] && [[ -f "$override" ]]; then
    if [[ -z "${STACK_COMPOSE_EXTRA_FILES:-}" ]]; then
      export STACK_COMPOSE_EXTRA_FILES="$override"
    else
      export STACK_COMPOSE_EXTRA_FILES="${STACK_COMPOSE_EXTRA_FILES}:${override}"
    fi
  fi
}

# -----------------------------------------------------------------------------
# create / destroy / list / inspect / gc
# -----------------------------------------------------------------------------

stack_sandbox_create() {
  local name="" ttl="1h" run_hooks=1 quiet=0
  while (( $# > 0 )); do
    case $1 in
      --name)       name=$2; shift 2 ;;
      --name=*)     name=${1#*=}; shift ;;
      --ttl)        ttl=$2; shift 2 ;;
      --ttl=*)      ttl=${1#*=}; shift ;;
      --no-hooks)   run_hooks=0; shift ;;
      --quiet|-q)   quiet=1; shift ;;
      *) stack_fail "unknown flag for sandbox create: $1" \
                    "Supported:  --name <label>   --ttl <duration>   --no-hooks   --quiet"; return 1 ;;
    esac
  done

  # Parse TTL → seconds. Accepts "30s", "10m", "2h", or bare seconds.
  local ttl_seconds
  ttl_seconds=$(stack_sandbox_parse_duration "$ttl") || {
    stack_fail "invalid --ttl: $ttl" "Use a suffix:  30s | 10m | 2h"
    return 1
  }

  # Concurrent-cap check.
  local cap current
  cap=$(stack_manifest features.sandbox_max_concurrent "$STACK_SANDBOX_MAX_DEFAULT")
  current=$(stack_sandbox_count_active)
  if (( current >= cap )); then
    stack_fail "Concurrent sandbox cap reached ($current / $cap)." \
               "Destroy one with:  stack sandbox destroy <id>   or raise features.sandbox_max_concurrent in manifest.yaml."
    return 1
  fi

  # Generate ID + override file.
  local id cproj override
  id=$(stack_sandbox_new_id)
  cproj=$(stack_sandbox_compose_project "$id")
  override=$(stack_sandbox_write_override "$id")

  local profile compose_file
  profile=$(stack_default_profile)
  compose_file=$(stack_compose_file "$profile")

  (( quiet )) || stack_step "Create sandbox: $id"

  # Scope all subsequent operations to this sandbox.
  export STACK_COMPOSE_PROJECT_OVERRIDE="$cproj"
  export STACK_COMPOSE_EXTRA_FILES="$override"

  # Reuse the primary build's image when it exists — sandboxes don't need
  # their own multi-minute rebuilds. We tag the primary's image under the
  # sandbox's compose-project name so `compose up` (without --build) picks it
  # up without re-uploading the build context.
  local svc_app primary_image sandbox_image
  svc_app=$(stack_service_app)
  primary_image=$(stack_sandbox_primary_image_name "$svc_app")
  sandbox_image="${cproj}-${svc_app}"

  if docker image inspect "$primary_image" >/dev/null 2>&1; then
    (( quiet )) || stack_info "Reusing primary image: $primary_image → $sandbox_image"
    docker tag "$primary_image" "$sandbox_image" 2>/dev/null || true
  else
    (( quiet )) || stack_warn "Primary image $primary_image not found — first build will be slow."
    (( quiet )) || stack_hint "Run 'stack up' once first to seed the build cache, or accept the wait."
  fi

  (( quiet )) || stack_info "Booting compose (project=$cproj)"
  # No --build: use cached image if available; compose builds only if missing.
  if (( quiet )); then
    stack_compose "$profile" up -d >/dev/null 2>&1 || {
      rm -f "$override"
      stack_fail "sandbox $id failed to start (compose up)" \
                 "Try without --quiet to see the error, or:  stack sandbox destroy $id"
      return 1
    }
  else
    stack_compose "$profile" up -d || {
      rm -f "$override"
      stack_fail "sandbox $id failed to start" \
                 "Inspect with:  docker compose -f $compose_file -f $override -p $cproj logs"
      return 1
    }
  fi

  # Register in the shared dashboard registry so it shows up alongside primary
  # instances (tagged ephemeral so it gets the 🧪 badge in the dashboard).
  local now expires_at
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  expires_at=$(stack_sandbox_iso_offset "$ttl_seconds")
  stack_sandbox_register "$id" "$name" "$cproj" "$override" "$ttl_seconds" "$expires_at"

  # Lifecycle hooks (unless --no-hooks). In quiet mode we redirect all hook
  # output to stderr so stdout stays clean for the ID-only contract.
  local hooks_applied=false
  if (( run_hooks )); then
    (( quiet )) || stack_step "Lifecycle hooks (post_up)"
    if (( quiet )); then
      if stack_lifecycle_run post_up >&2; then
        hooks_applied=true
        stack_sandbox_mark_hooks_applied "$id"
      fi
    else
      if stack_lifecycle_run post_up; then
        hooks_applied=true
        stack_sandbox_mark_hooks_applied "$id"
      else
        stack_warn "post_up hook failed — sandbox is up but bootstrap incomplete."
        stack_hint "Re-run hooks ad-hoc:  stack sandbox $id lifecycle run post_up"
      fi
    fi
  fi

  (( quiet )) || {
    stack_step "Sandbox ready"
    stack_ok "id:              $id"
    [[ -n "$name" ]] && stack_ok "name:            $name"
    stack_ok "compose project: $cproj"
    stack_ok "ttl:             $ttl  (expires $expires_at)"
    stack_ok "hooks applied:   $hooks_applied"
    printf "\n  %sExercise it:%s\n" "${C_DIM}" "${C_RESET}"
    printf "    stack sandbox %s exec wget -qO- http://localhost:4100/api/health\n" "$id"
    printf "    stack sandbox %s psql -c 'SELECT count(*) FROM projects'\n" "$id"
    printf "    stack sandbox %s logs core --since 1m\n" "$id"
    printf "    stack sandbox %s seed apply <name>\n" "$id"
    printf "    stack sandbox %s exec sh -c '<arbitrary shell>'    %s# busybox sh inside the app container%s\n" "$id" "${C_DIM}" "${C_RESET}"
    printf "\n  %sDestroy when done:%s\n" "${C_DIM}" "${C_RESET}"
    printf "    stack sandbox destroy %s\n\n" "$id"
  }

  # Final structured output for AI / scripts.
  if (( quiet )); then
    # Just the ID on stdout.
    printf "%s\n" "$id"
  else
    # JSON to stdout (so callers can parse if they pipe).
    stack_sandbox_inspect "$id"
  fi
}

stack_sandbox_destroy() {
  local id=$1
  if [[ -z "$id" ]]; then
    stack_fail "sandbox destroy requires an id (or --all)" "List sandboxes:  stack sandbox list"
    return 1
  fi

  local entry profile cproj override
  entry=$(stack_sandbox_get "$id") || {
    stack_fail "sandbox not found: $id" "List sandboxes:  stack sandbox list"
    return 1
  }

  cproj=$(printf "%s" "$entry" | python3 -c "import sys,json;print(json.load(sys.stdin)['compose_project'])")
  override=$(printf "%s" "$entry" | python3 -c "import sys,json;print(json.load(sys.stdin).get('override_file',''))")

  stack_step "Destroy sandbox: $id"

  profile=$(stack_default_profile)
  # Scope to the sandbox for the down call.
  STACK_COMPOSE_PROJECT_OVERRIDE="$cproj" \
  STACK_COMPOSE_EXTRA_FILES="$override" \
    stack_compose "$profile" down --volumes 2>&1 | tail -10

  stack_state_unregister "$id"
  [[ -f "$override" ]] && rm -f "$override"
  stack_ok "Destroyed: $id"
}

stack_sandbox_destroy_all() {
  local slug
  slug=$(stack_project_slug)
  local ids
  ids=$(python3 - "$STACK_REGISTRY" "$slug" <<'PY'
import json, sys
file, slug = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(0)
for inst in data.get("instances", []):
    if inst.get("kind") == "sandbox" and inst.get("project") == slug:
        print(inst["id"])
PY
)
  if [[ -z "$ids" ]]; then
    stack_info "No sandboxes for project=$slug — nothing to destroy."
    return 0
  fi
  while IFS= read -r id; do
    [[ -n "$id" ]] && stack_sandbox_destroy "$id" || true
  done <<< "$ids"
}

stack_sandbox_list() {
  python3 - "$STACK_REGISTRY" <<'PY'
import json, sys, os
from datetime import datetime, timezone
file = sys.argv[1]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    print("(no registry)")
    raise SystemExit(0)
sandboxes = [i for i in data.get("instances", []) if i.get("kind") == "sandbox"]
if not sandboxes:
    print("(no active sandboxes)")
    raise SystemExit(0)
now = datetime.now(timezone.utc)
print()
print(f"  {'ID':<28} {'NAME':<20} {'PROJECT':<10} {'AGE':<10} {'EXPIRES IN':<14} {'HOOKS'}")
print(f"  {'-'*28} {'-'*20} {'-'*10} {'-'*10} {'-'*14} {'-'*5}")
for s in sandboxes:
    try:
        created = datetime.fromisoformat(s["created_at"].replace("Z", "+00:00"))
        age_sec = int((now - created).total_seconds())
    except Exception:
        age_sec = 0
    try:
        expires = datetime.fromisoformat(s["expires_at"].replace("Z", "+00:00"))
        ttl_sec = int((expires - now).total_seconds())
    except Exception:
        ttl_sec = 0
    def fmt(sec):
        if sec < 0: return "EXPIRED"
        if sec < 60: return f"{sec}s"
        if sec < 3600: return f"{sec//60}m"
        return f"{sec//3600}h {(sec%3600)//60}m"
    name = s.get("name") or "—"
    hooks = "yes" if s.get("hooks_applied") else "no"
    print(f"  {s['id']:<28} {name:<20} {s['project']:<10} {fmt(age_sec):<10} {fmt(ttl_sec):<14} {hooks}")
print()
PY
}

stack_sandbox_inspect() {
  local id=$1
  python3 - "$STACK_REGISTRY" "$id" <<'PY'
import json, sys
file, target = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(1)
for inst in data.get("instances", []):
    if inst.get("id") == target and inst.get("kind") == "sandbox":
        print(json.dumps(inst, indent=2))
        sys.exit(0)
sys.exit(1)
PY
}

stack_sandbox_gc() {
  local expired
  expired=$(python3 - "$STACK_REGISTRY" <<'PY' 2>/dev/null
import json, sys
from datetime import datetime, timezone
file = sys.argv[1]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(0)
now = datetime.now(timezone.utc)
for inst in data.get("instances", []):
    if inst.get("kind") != "sandbox": continue
    try:
        exp = datetime.fromisoformat(inst["expires_at"].replace("Z", "+00:00"))
    except Exception:
        continue
    if exp < now:
        print(inst["id"])
PY
) || true
  [[ -z "$expired" ]] && return 0
  # Read into an array first to avoid the stdin-consumption issue we hit in lifecycle.sh.
  local -a expired_ids=()
  local id
  while IFS= read -r id; do
    [[ -n "$id" ]] && expired_ids+=("$id")
  done <<< "$expired"
  for id in "${expired_ids[@]}"; do
    stack_info "GC: sandbox $id expired — destroying"
    stack_sandbox_destroy "$id" 2>/dev/null || true
  done
}

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

stack_sandbox_count_active() {
  local slug
  slug=$(stack_project_slug)
  python3 - "$STACK_REGISTRY" "$slug" <<'PY' 2>/dev/null
import json, sys
file, slug = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    print(0); sys.exit(0)
n = sum(1 for i in data.get("instances", []) if i.get("kind") == "sandbox" and i.get("project") == slug)
print(n)
PY
}

stack_sandbox_parse_duration() {
  local s=$1
  if [[ "$s" =~ ^([0-9]+)$ ]]; then
    printf "%d" "${BASH_REMATCH[1]}"
  elif [[ "$s" =~ ^([0-9]+)s$ ]]; then
    printf "%d" "${BASH_REMATCH[1]}"
  elif [[ "$s" =~ ^([0-9]+)m$ ]]; then
    printf "%d" $(( ${BASH_REMATCH[1]} * 60 ))
  elif [[ "$s" =~ ^([0-9]+)h$ ]]; then
    printf "%d" $(( ${BASH_REMATCH[1]} * 3600 ))
  elif [[ "$s" =~ ^([0-9]+)d$ ]]; then
    printf "%d" $(( ${BASH_REMATCH[1]} * 86400 ))
  else
    return 1
  fi
}

stack_sandbox_iso_offset() {
  local secs=$1
  python3 -c "
from datetime import datetime, timezone, timedelta
print((datetime.now(timezone.utc) + timedelta(seconds=$secs)).isoformat().replace('+00:00', 'Z'))
"
}

stack_sandbox_register() {
  local id=$1 name=$2 cproj=$3 override=$4 ttl=$5 expires_at=$6
  local slug worktree path now
  slug=$(stack_project_slug)
  worktree=$(stack_current_worktree)
  path=$STACK_REPO_ROOT
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  python3 - <<PY
import json
file = "$STACK_REGISTRY"
entry = {
    "id": "$id",
    "kind": "sandbox",
    "name": "$name",
    "project": "$slug",
    "worktree": "$worktree",
    "path": "$path",
    "profile": "$(stack_default_profile)",
    "compose_project": "$cproj",
    "override_file": "$override",
    "ephemeral": True,
    "ports": {},
    "urls": [],
    "ttl_seconds": $ttl,
    "created_at": "$now",
    "expires_at": "$expires_at",
    "hooks_applied": False,
}
try:
    with open(file) as f: data = json.load(f)
except Exception:
    data = {"version": 1, "instances": []}
others = [i for i in data.get("instances", []) if i.get("id") != "$id"]
data["instances"] = others + [entry]
with open(file, "w") as f:
    json.dump(data, f, indent=2)
PY
}

stack_sandbox_mark_hooks_applied() {
  local id=$1
  python3 - "$STACK_REGISTRY" "$id" <<'PY' 2>/dev/null
import json, sys
file, target = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(0)
for inst in data.get("instances", []):
    if inst.get("id") == target:
        inst["hooks_applied"] = True
with open(file, "w") as f:
    json.dump(data, f, indent=2)
PY
}

# Determine the image name compose would build for the PRIMARY stack's app
# service. Matches compose's default tagging: <project>-<service>.
stack_sandbox_primary_image_name() {
  local svc=$1
  local slug worktree primary_proj
  slug=$(stack_project_slug)
  worktree=$(stack_current_worktree)
  # Replicates stack_compose_project_name's transformation without the override.
  primary_proj=$(printf "%s@%s" "$slug" "$worktree" | tr '@' '_' | tr '#' '_' | tr '/' '-' | tr '[:upper:]' '[:lower:]')
  printf "%s-%s" "$primary_proj" "$svc"
}

stack_sandbox_get() {
  local id=$1
  python3 - "$STACK_REGISTRY" "$id" <<'PY'
import json, sys
file, target = sys.argv[1], sys.argv[2]
try:
    with open(file) as f: data = json.load(f)
except Exception:
    sys.exit(1)
for inst in data.get("instances", []):
    if inst.get("id") == target and inst.get("kind") == "sandbox":
        print(json.dumps(inst))
        sys.exit(0)
sys.exit(1)
PY
}
